### ISSUE TITLE
Text background change

### ISSUE THREAD

**Issue by AetherPrior** [aeris170/MARS-Theme-Engine#2]
The themes don't seem to modify the background for the code window. Is there a setting I missed?

**Comment by aeris170** [comment]
No, you didn't miss anything themes don't modify the editor (code window). In order to change the background of the editor, go to _Settings>Editor_. 

I kept the code of MARS as is, and added the theme support on top. Since MARS already had a way to alter the look of the editor I didn't integrate themes into the editor window.

**Comment by AetherPrior** [comment]
Looks like there's no way to change the background color to dark then, atleast without using the eclipse version or altering the source.

**Comment by aeris170** [comment]
Yes you are right. MARS doesn't allow the editor background to change, I didn't notice it. I'll try implement is ASAP. Contributions are also welcome.

**Comment by aeris170** [comment]
The feature is implemented, it is yet to be tested on Linux and Mac platforms. Enjoy @AetherPrior!!! :)

**Comment by AetherPrior** [comment]
That was FAST

**Comment by AetherPrior** [comment]
Seems to work fine on Arch Linux. Though may appear crude, but hey! It solves the problem.

**Comment by aeris170** [comment]
> Seems to work fine on Arch Linux. Though may appear crude, but hey! It solves the problem.

Hey @AetherPrior thank you for testing! Can I get the details of your operating system so I can add it the tested platforms list? A version number/release date would do the job. Also, I'm happy you liked the change. :)

**Comment by AetherPrior** [comment]
OS: Arch Linux, Sun, 13 Sep 2020 23:44:55 +0000
Kernel: Linux version 5.8.9-arch2-1
Architecture: x86_64
