### ISSUE TITLE
Theme Only Affecting UI

### ISSUE THREAD

**Issue by TobsterStrudel** [aeris170/MARS-Theme-Engine#3]
The biggest reason for me wanting a MARS theme engine was to save my eyes from the blinding white. Although this is fixed mostly with this program, the place I look at the most (the actual program editor and registry table) is still white no matter what.
Is there a way to change the background color and/or the text color to accommodate?

**Comment by TobsterStrudel** [comment]
Settings > Editor > Text Editor.
My bad.

**Comment by aeris170** [comment]
It's OK, I'm pinning this issue so others who may miss it won't waste time :)

**Comment by Megaproalex** [comment]
<img width="804" height="610" alt="Image" src="https://github.com/user-attachments/assets/f2221fce-64cb-4ae1-b794-b08765cec6ff" />

Everything seems to work, thank you for developing this eye saving engine. 

Nonetheless if someone ever will comeback to this there are at least two further improvements I think could be made: making the design of the above interface of the helper screen more readable; and I also could not find a way to change the colour of the register table still.
